export default {
  login: 'john-smilga',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/john-smilga',
  html_url: 'https://github.com/john-smilga',
  followers_url: 'https://api.github.com/users/john-smilga/followers',
  following_url:
    'https://api.github.com/users/john-smilga/following{/other_user}',
  gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
  organizations_url: 'https://api.github.com/users/john-smilga/orgs',
  repos_url: 'https://api.github.com/users/john-smilga/repos',
  events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/john-smilga/received_events',
  type: 'User',
  site_admin: false,
  name: 'John Smilga',
  company: 'Coding Addict',
  blog: 'www.johnsmilga.com',
  location: 'Los Angeles',
  email: null,
  hireable: null,
  bio: 'Creator of Coding Addict',
  twitter_username: 'john_smilga',
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2020-07-08T05:01:32Z',
};



// export default {
// login: "mojombo",
// id: 1,
// node_id: "MDQ6VXNlcjE=",
// avatar_url: "https://avatars.githubusercontent.com/u/1?v=4",
// gravatar_id: "",
// url: "https://api.github.com/users/mojombo",
// html_url: "https://github.com/mojombo",
// followers_url: "https://api.github.com/users/mojombo/followers",
// following_url: "https://api.github.com/users/mojombo/following{/other_user}",
// gists_url: "https://api.github.com/users/mojombo/gists{/gist_id}",
// starred_url: "https://api.github.com/users/mojombo/starred{/owner}{/repo}",
// subscriptions_url: "https://api.github.com/users/mojombo/subscriptions",
// organizations_url: "https://api.github.com/users/mojombo/orgs",
// repos_url: "https://api.github.com/users/mojombo/repos",
// events_url: "https://api.github.com/users/mojombo/events{/privacy}",
// received_events_url: "https://api.github.com/users/mojombo/received_events",
// type: "User",
// site_admin: false,
// name: "Tom Preston-Werner",
// company: "@chatterbugapp, @redwoodjs, @preston-werner-ventures ",
// blog : "http://tom.preston-werner.com",
// location: "San Francisco",
// email: null,
// hireable: null,
// bio: null,
// twitter_username: "mojombo",
// public_repos: 63,
// public_gists: 62,
// followers: 22982,
// following: 11,
// created_at: "2007-10-20T05:24:19Z",
// updated_at: "2022-04-03T23:40:06Z"
// }

